<!--<h1> Page <?= $page ?> de Parade Ox (Cécile JEANNEAU)</h1>-->

<section class="articles section--grid">
    
    <article class="">
        <h2><i class="fa fa-graduation-cap" aria-label="Formations"></i></h2>
        <ul>
            <li>Développeur Intégrateur Web et Web mobile à la 3WA 2022</li>
            <li>Designer Web au GRETA 2021</li>
            <li>BPJEPS dominante Arts numériques à l'IBEP</li>
            <li>Diplôme National d'Arts Plastiques en Création Numérique à l'EESI</li>
        </ul>
    </article>
    
    <article class="contact">
        <img src="./assets/cecile_jeanneau.jpg" alt="ma photo">
    </article>
    
    <article class="">
        <h2><i class="fa fa-briefcase" aria-label="Expériences"></i></h2>

        <ul>
            <li>Intégratrice WordPress à Breizh Me Up en tant qu'associée 2021</li>
            <li>Designeuse Web en stage au GRETA 2021</li>
            <li>Animatrice socioculturelle dans diverses mairies de 2016 à 2018</li>
            <li>Chargée de Communication en mission Service Civique à l'UFCV 2015</li>
        </ul>
    </article>
    
</section>


<section class="articles section--no-grid">
    
    <article>
        <h3>Mon parcours :</h3>
        <p>Issue d’un parcours d’Arts Appliqués, je m’étais orientée vers le socioculturel avec une dominante numérique. L’informatique étant une passion familiale ne m’ayant jamais quittée et stimulant ma curiosité intellectuelle, j’ai souhaité me spécialiser.
Suite à une formation intensive en développement web, je recherche un apprentissage d’un an en Fullstack.</p>
    </article>
    
</section>

