<h1> Page <?= $page ?> de Parade Ox (Cécile JEANNEAU)</h1>


<section>
    <article class="contact">
        <img src="./assets/cecile_jeanneau.jpg" alt="ma photo">
        <h5>Cécile JEANNEAU</h5>
    </article>
    <article>
        <h2>En quelques mots</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, facilis, quo, quaerat temporibus dignissimos ut doloremque vero voluptates cupiditate sequi at accusantium delectus voluptas non sint voluptatibus voluptate sunt debitis nam ipsa autem cum dolores eligendi tempore accusamus consequuntur commodi hic voluptatum consequatur dicta incidunt quam aspernatur ea necessitatibus velit maiores nemo.</p>
    </article>
</section>

<section>
    <h3>Formations</h3>
    <ul>
        <li>Développeur Intégrateur Web et Web mobile à la 3WA 2022</li>
        <li>Designer Web au GRETA 2021</li>
        <li>BPJEPS dominante Arts numériques à l'IBEP</li>
        <li>Diplôme National d'Arts Plastiques en Création Numérique à l'EESI</li>
    </ul>
</section>

<section>
    <h3>Expériences</h3>
    <ul>
        <li>Intégratrice WordPress à Breizh Me Up en tant qu'associée 2021</li>
        <li>Designeuse Web en stage au GRETA 2021</li>
        <li>Animatrice socioculturelle dans diverses mairies de 2016 à 2018</li>
        <li>Chargée de Communication en mission Service Civique à l'UFCV 2015</li>
    </ul>
</section>