<!--HERE THE AUTHENTICATION FORM-->
<section class="articles section--grid">
    <article>
<form action="send-contact" method="post" enctype="multipart/form-data" name="contact">

    <h1>Déposez ici votre offre d'emploi ou posez vos questions !</h1>

    <input type="text" name="name" placeholder="Votre nom et entreprise*" autocomplete="off" required>

    <input type="text" name="email" placeholder="Votre Email *" autocomplete="off" required>

    <input type="tel" name="phone" placeholder="Votre numéro de téléphone *" pattern="[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{2}" autocomplete="off">
    <small>Format: 06-06-06-06-06</small>

    <textarea name="content" rows="30" cols="100" minlength="100" maxlength="3000" required>Votre message, votre offre, détails ou questions ...</textarea>

    <label>future fonctionnalité BIENTÔT !! ->  déposez votre offre d'emploi ici : </label>
    <input type="file" name="fileToUpload" id="fileToUpload" disabled>

    <input type="submit" name="submit" value="Send">

</form>
</article>
</section>