<form action="upload" method="post" enctype="multipart/form-data">
              
              <h1> Voici le <?= $page ?> </h1>
              
              <textarea name="description" rows="20" cols="50" maxlength="150" required>Écrire la description ici *</textarea>
              <input type="text" name="name" placeholder="Nom de l'image *" required>
              <input type="text" name="alt" placeholder="Texte alt SEO/accessibilité *" required>
              <input type="text" name="category" placeholder="Nom de la catégorie *" required>
              
              <label>Sélectionner une image à télécharger : </label>
              <input type="file" name="fileToUpload" id="fileToUpload" multiple required>
              
              <input type="submit" value="Télécharger" name="submit">
</form>