<h1> Bienvenue !! </h1>

<section>
    <article class="contact">
        <img src="./assets/cecile_jeanneau.jpg" alt="ma photo">
        <h5>Cécile JEANNEAU</h5>
    </article>
    <article>
        <h2>En quelques mots</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, facilis, quo, quaerat temporibus dignissimos ut doloremque vero voluptates cupiditate sequi at accusantium delectus voluptas non sint voluptatibus voluptate sunt debitis nam ipsa autem cum dolores eligendi tempore accusamus consequuntur commodi hic voluptatum consequatur dicta incidunt quam aspernatur ea necessitatibus velit maiores nemo.</p>
        <a href="a-propos">Découvrir mon parcours</a>
        <!--page contact-->
    </article>
</section>
    

<section>
    
    <h2>Mes dernières réalisations</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt, voluptate inventore sequi voluptas explicabo eius iure blanditiis numquam atque asperiores doloribus vitae optio minus suscipit ipsa harum dolor eligendi autem cupiditate quaerat ex nisi animi repudiandae in aut quisquam quis praesentium eaque reprehenderit pariatur quidem saepe veritatis officiis cum illum commodi velit assumenda molestias beatae culpa consectetur tenetur at ut neque nihil hic quas dolorum ipsam minima alias!</p>
    
</section>


<section>
    
    <article class="contact">
        <img src="./uploads/cae9fbdb85ad7444865e.jpg" alt="">
        <h5>photo du projet</h5>
    </article>
    
    <article class="project-article">
        
        <h3>Projet 1</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, facilis, quo, quaerat temporibus dignissimos ut doloremque vero voluptates cupiditate sequi at accusantium delectus voluptas non sint voluptatibus voluptate sunt debitis nam ipsa autem cum dolores eligendi tempore accusamus consequuntur commodi hic voluptatum consequatur dicta incidunt quam aspernatur ea necessitatibus velit maiores nemo.</p>
        
    </article>
    
    <article class="project-article">
        
        <h3>Projet 2</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, facilis, quo, quaerat temporibus dignissimos ut doloremque vero voluptates cupiditate sequi at accusantium delectus voluptas non sint voluptatibus voluptate sunt debitis nam ipsa autem cum dolores eligendi tempore accusamus consequuntur commodi hic voluptatum consequatur dicta incidunt quam aspernatur ea necessitatibus velit maiores nemo.</p>
        
    </article>
    
    <article class="contact">
        <img src="./uploads/cae9fbdb85ad7444865e.jpg" alt="">
        <h5>photo du projet</h5>
    </article>
    
    <article class="contact">
        <img src="./uploads/cae9fbdb85ad7444865e.jpg" alt="">
        <h5>photo du projet</h5>
    </article>
    
    <article class="project-article">
        
        <h3>Projet 3</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, facilis, quo, quaerat temporibus dignissimos ut doloremque vero voluptates cupiditate sequi at accusantium delectus voluptas non sint voluptatibus voluptate sunt debitis nam ipsa autem cum dolores eligendi tempore accusamus consequuntur commodi hic voluptatum consequatur dicta incidunt quam aspernatur ea necessitatibus velit maiores nemo.</p>
        
    </article>
    
</section>