<h1> Bienvenue !! </h1>

<section class="articles section--grid">
    <article class="contact">
        <a href="a-propos"><img class="img__modal--hidden" src="./assets/cecile_jeanneau.jpg" alt="ma photo"></a>
        <h5>Cécile JEANNEAU</h5>
    </article>
    <article>
        <h2>En quelques mots</h2>
        <p>Issue d’un parcours d’Arts Appliqués, je m’étais orientée vers le socioculturel avec une dominante numérique. L’informatique étant une passion familiale ne m’ayant jamais quittée et stimulant ma curiosité intellectuelle, j’ai souhaité me spécialiser.
Suite à une formation intensive en développement web, je recherche un apprentissage d’un an en Fullstack.</p>
        <a href="a-propos">Découvrir mon parcours</a>
        <!--page contact-->
    </article>
</section>
    

<section class="articles section--grid">
    
    <h2>Mes dernières réalisations</h2>
    <p>Parmis de nombreux projets artistiques, de webdesign et de développement web, voici les 3 derniers : </p>
    
</section>


<section class="articles section--grid">
    
    <article class="contact">
        <a href="medias"><img class="img__modal--hidden" src="./uploads/8cc0d6198d7e8b21a0aa.jpg" alt=""></a>
        <h5>photo du projet</h5>
    </article>
    
    <article class="project-article">
        
        <h3>Projet 1</h3>
        <p>vidéo promotionnelle pour un tatoueur</p>
        
    </article>
    
    <article class="project-article">
        
        <h3>Projet 2</h3>
        <p>screen breizh me up site web</p>
        
    </article>
    
    <article class="contact">
        <a href="medias"><img class="img__modal--hidden" src="./uploads/fab418baef8b363c0eb4.jpg" alt=""></a>
        <h5>photo du projet</h5>
    </article>
    
    <article class="contact">
        <a href="medias"><img class="img__modal--hidden" src="./uploads/6e772dea5b8ce34ea48b.jpg" alt=""></a>
        <h5>photo du projet</h5>
    </article>
    
    <article class="project-article">
        
        <h3>Projet 3</h3>
        <p>affiche laboratoire artistique populaire design print</p>
        
    </article>
    
</section>

