<!DOCTYPE html>
<html>
    
    <head>
        
        <meta charset="utf-8" />
        <title>Parade Ox</title>
        <link rel="stylesheet" href="./assets/style.css" type="text/css" />
    
    </head>
    
    <body>
        
        <header>
            <nav>
                <ul>
                    <li><img src=""></li>
                    <li>Accueil</li>
                    <li>À propos</li>
                    <li>Réalisations</li>
                    <li>Contact</li>
                </ul>
            </nav>
            <h1>PARADE OX</h1>
            <p>Web Designer & Developer</p>
            <ul>
                <li><span></span></li>
                <li><span></span></li>
                <li><span></span></li>
            </ul>
        
        </header>
        
        <main>
            
            <?php require "./templates/".$page.".phtml"; ?>
            
        </main>
        
        <footer>
            
            <p>footer space</p>
        
        </footer>
        
    </body>
    
</html>