<!--HERE THE AUTHENTICATION FORM-->

<form action="login-check-opti" method="POST" name="login">
    
    <h1>Connexion</h1>
    
    <input type="text" name="username" 
  placeholder="Identifiant *" autocomplete="off" required>
  
    <input type="text" name="email" 
  placeholder="E-mail *" autocomplete="off" required>
  
    <input type="password" name="password" 
  placeholder="Mot de passe *" autocomplete="off" required>
  
    <input type="submit" name="submit" 
  value="Connexion">
  
    <p> Pas de compte ? <a href="inscription">Crée ton compte membre !</a> </p>
  
</form>