<section class="articles section--grid">
            <?php foreach($ajaxSearch as $idIndex=>$result) { ?>
				<article class="card">

					<h3><?= htmlspecialchars($result['name']) ?></h3>
					<figure>
						<img id="<?= $idIndex ?>" class="img__modal--hidden" src="./uploads/<?= $result['file_name'] ?>.<?= $result['file_type'] ?>" alt="<?= $result['alt'] ?>" role="button">
						<figcaption> <?= htmlspecialchars($result['description']) ?> </figcaption>
					</figure>
					<p><?= nl2br(htmlspecialchars($result['category'])) ?></p>
				</article>
            <?php } ?>
</section>