<section class="articles section--grid" id="answerList">
            <?php foreach($this->getMedias() as $idIndex=>$result) { ?>
            
				<article class="card">
					<h3><?= htmlspecialchars($result['name']) ?></h3>
					<figure>
						<img id="<?= $idIndex ?>" class="img__modal--hidden" src="./uploads/<?= $result['file_name'] ?>.<?= $result['file_type'] ?>" alt="<?= $result['alt'] ?>" role="button">
						<figcaption> <?= htmlspecialchars($result['description']) ?> </figcaption>
					</figure>
					<cite><?= nl2br(htmlspecialchars($result['category'])) ?></cite>
				</article>
				
            <?php } ?>
</section>

<section class="articles section--no-grid">
	<article class="search">
		<h4><i class="fa fa-search" aria-hidden="true"></i></h4>
		<label for="searchbar"> Rechercher une image par sa catégorie : </label>
		<input type="text" id="searchbar" name="searchbar" placeholder="rechercher une catégorie">
	</article>
</section>

<!--foreach($array as $key=>$value) {-->
<!--    // do stuff-->
<!--}-->
<!--$key is the index of each $array element-->